# options:
#    auto-update - Github 新版本自動檢查並更新
#    armor-update-interval - 粘液科技護甲效果更新週期
#    enable-armor-effects - 護甲效果的開關
#    chat-prefix - 粘液科技所有消息的前綴
#    auto-save-delay-in-minutes - 自動保存數據的週期, 單位為分鐘
#    legacy-ore-washer - 是否使用舊版的洗礦機機制
#    legacy-dust-washer - 是否使用舊版的除塵機機制
#    legacy-ore-grinder - 是否使用舊版的碎礦機機制
#    language - 粘液科技文本語言 (不包括物品)
#    enable-translations - 多語言功能
#    backwards-compatibility - 物品向後兼容模式, 關閉後物品會使用新版物品系統
#                             將會提升性能
#    log-duplicate-block-entries - 是否輸出發現重複方塊的警告
#    burn-players-when-radioactive - 是否在當玩家暴露在輻射中時灼燒玩家
#    drop-excess-sf-give-items - 是否在揹包已滿時使用命令給予 Slimefun 物品直接掉落溢出的物品
#    backup-data - 自動備份數據
#    bypass-environment-check - 跳過兼容性檢查 (注意: 打開後將不予接受問題反饋)
options:
  auto-update: true
  chat-prefix: '&a&lSlimefun 4 &7> '
  armor-update-interval: 10
  enable-armor-effects: true
  enable-radiation: true
  radiation-update-interval: 1
  radiation-grace-period: 15
  rainbow-armor-update-interval: 3
  auto-save-delay-in-minutes: 10
  legacy-ore-washer: false
  legacy-dust-washer: false
  legacy-ore-grinder: true
  language: zh-TW
  enable-translations: true
  log-duplicate-block-entries: true
  burn-players-when-radioactive: true
  drop-excess-sf-give-items: false
  backup-data: true
  drop-block-creative: true
  bypass-environment-check: false
  bypass-item-length-check: false
  max-gps-waypoints: 21

guide:
  # 是否在指南中展示原版物品合成配方
  show-vanilla-recipes: true
  # 是否在玩家第一次進入服務器時自動贈送粘液科技指南
  receive-on-first-join: true
  # 是否在搜索中顯示隱藏物品
  show-hidden-item-groups-in-search: false

researches:
  # 是否允許創造模式玩家免費解鎖研究
  free-in-creative-mode: true
  # 是否在解鎖時燃放煙花
  enable-fireworks: true
  # 是否使用遊戲幣替代使用經驗解鎖
  use-money-unlock: false
  # 經驗自動轉換到遊戲幣倍率
  currency-cost-convert-rate: 25.0
  # 是否禁用解鎖研究時的動畫
  disable-learning-animation: false

URID:
  info-delay: 3000
  custom-ticker-delay: 10
  enable-tickers: true

networks:
  max-size: 200
  cargo-ticker-delay: 0
  enable-visualizer: true
  delete-excess-items: false

talismans:
  use-actionbar: true

metrics:
  auto-update: false

backpack:
  # 揹包所有者離線時是否允許揹包被打開
  allow-open-when-owner-offline: true

research-ranks:
  - 小雞
  - 牛牛君
  - 蜘蛛
  - 村民
  - 開拓者
  - 童生
  - 實習生
  - 不合格生
  - 學生
  - 笨拙學徒
  - 學徒
  - 熟練學徒
  - 法師學徒
  - 傑出法師
  - 年輕魔術師
  - 笨拙魔術師
  - 普通魔術師
  - 魔術師
  - 熟練魔術師
  - 特技魔術師
  - 慣用魔術師
  - 傑出魔術師
  - 笨拙巫師
  - 巫師
  - 普通巫師 
  - 特技巫師
  - 傑出巫師
  - 卓越巫師
  - 年輕大師
  - 笨拙大師
  - 實習大師
  - 合格大師
  - 大師
  - 特技大師
  - 傑出大師
  - 卓越大師
  - 精通大師
  - 天選之子
